title: JingleTube
emoji: ğŸ¤
colorFrom: purple
colorTo: pink
sdk: gradio
sdk_version: 4.19.0
app_file: app.py
pinned: false
license: mit
short_description: KaraokÃª com pontuaÃ§Ã£o - Cante e compita!
